web:
    build: apache
    ports:
        - "80:80"
    links:
        - db
    volumes:
        - ../site/:/var/www/html/

db:
    build: mysql
    environment:
        MYSQL_ROOT_PASSWORD: beo8hkii
        MYSQL_DATABASE: brainspell
    # Seems to create trouble...
    # volumes:
    #     - ./mysql/storage/:/var/lib/mysql/
