web:
    build: apache
    ports:
        - "8000:80"
    links:
        - db
    volumes:
        - ../site/:/var/www/html/

db:
    build: mysql
    environment:
        MYSQL_ROOT_PASSWORD: beo8hkii
        MYSQL_DATABASE: brainspell
    volumes:
        # Creates trouble unless we make it world-writable...
        # - ./mysql/storage/:/var/lib/mysql/
        - ./mysql/data:/docker-entrypoint-initdb.d
