web:
    build: apache
    ports:
        - "80:80"
    links:
        - db
    volumes:
        - ../site/:/var/www/html/

db:
    build: mysql
    environment:
        MYSQL_ROOT_PASSWORD: beo8hkii
        MYSQL_DATABASE: brainspell
    volumes:
        - ../tmp/mysql:/var/lib/mysql
